# Generated by Django 3.0.4 on 2020-04-13 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200413_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('4cfb93ac-112b-4480-98eb-b01bca7251b1'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='join_code',
            field=models.CharField(default='ijud', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('800d0911-589d-4613-a3ec-5a91a2e0ec07'), primary_key=True, serialize=False, unique=True),
        ),
    ]
