# Generated by Django 3.0.4 on 2020-04-13 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20200413_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('35aa4b0e-5293-4654-8507-f6e2fe96d16c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='join_code',
            field=models.CharField(default='qapd', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('8a1686a7-6f29-4618-b6d6-c25219c14612'), primary_key=True, serialize=False, unique=True),
        ),
    ]
